### ISSUE TITLE
Currying?

### ISSUE THREAD

**Issue by shadowhand** [pawaclawczyk/scalp#21]
I see that scalp has a partial function, but it looks like said function expects that all arguments will be passed during invocation. What would it take to add a currying?

**Comment by pawaclawczyk** [comment]
I think it's great idea and currying will be a nice tool next to PFA.

I assume that `curry` function should take N-arguments function and return a function with N-1 arity. With this assumption it should return the passed function for 0 or 1 argument functions.

```php
$cuboidVolume = function (int $a, int $b, int $h): int {
    return $a * $b * $c;
};

$curriedVolume = curry($cuboidVolume);

$res0 = $curriedVolume(3, 2)(5);

// $res0 === 30
```

I'm not sure if we need reverse function -- `uncurry`.

I think I'll be done with the first implementation this week.

**Comment by shadowhand** [comment]
Yes that syntax looks right. FWIW, there are a few implementations of currying for PHP already. In fact I wrote an implementation [a while back](https://github.com/php-fp/php-fp-combinators/pull/4/commits/e21a95d161d42a5065c0617544c18fa134c9d5da) that never went anywhere.

**Comment by pawaclawczyk** [comment]
@shadowhand I've created PR #22 , if you're interested please make code review.

I plan for the future to add type checking at the moment of argument application to curried function, not on the final function call.
